### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (250x48 and 6x32)

### ISSUE THREAD

**Issue by baoping-ma** [bu-air-lab/guide_dog#1]
Hello, this is a very meaningful work, I want to repeat, but after the completion of the training, the running test (python play.py) is the following error, can you help to answer it? Be grateful~

"""
Loading model from: /home/mbp/guide_dog-main/logs/guide_dog/estimator4/model_1500.pt
Exported policy as jit script to:  /home/mbp/guide_dog-main/logs/guide_dog/exported/policies
Traceback (most recent call last):
  File "play.py", line 155, in <module>
    play(args)
  File "play.py", line 103, in play
    estimated_force = force_estimator(obs_history)
  File "/home/mbp/anaconda3/envs/guidedog/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mbp/anaconda3/envs/guidedog/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mbp/guide_dog-main/guide_dog_ppo/guide_dog_ppo/modules/force_estimator.py", line 51, in forward
    x = self.activation(self.mlp_in(original_obs))
  File "/home/mbp/anaconda3/envs/guidedog/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mbp/anaconda3/envs/guidedog/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mbp/anaconda3/envs/guidedog/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (250x48 and 6x32)
""""

**Comment by 1903943257** [comment]
I have the same problem, have you solved it?
